### ISSUE TITLE
issue on save

### ISSUE THREAD

**Issue by KRASK52** [tbeswick96/BannerlordYetAnotherPartyOrganiser#41]
on save sometimes, not always, a pop up shows up saying

yetanotherpartyorganiser failed to find sorter configuration for the current save save_auto....exct

invalidoperationexception:
sequence contains no matching element

stack trace:
at system.linq.enumerable.first[tsource](ienumerable'1 source,func's predicate) at yapo.configuration.sorterconfigurationmanager.saveconfiguration() in 
B:\MBB\mod\yetanotherpartyorganiser\extension\configuration\sorterconfigurationmanager.cs:line 26

after which the game is still playable and still seems to save group info. seems to happen after combat. let me know if  you need anymore info

**Comment by tbeswick96** [comment]
Thanks for the report, will check this out

**Comment by tbeswick96** [comment]
@KRASK52 This has been fixed with 1.3.2, please can you update and test on your end to confirm the problem is fixed

**Comment by KRASK52** [comment]
have tested still getting error message.

null reference exception
object reference not set to an instance of an object.

stack  trace
yapo.configuration.sorterconfigurationmanager.saveconfigurations()
in
B:\mbb\mods\yetanotherpartyorganiser\extension\configuration\sorterconfigurationmanager.cs:line 27

I will try to see if it is a mod interaction and which mod

**Comment by KRASK52** [comment]
dosen't seem to be a mod interaction same message pops up with a clean mod install no other mods in module folder except modlib and aragas alt save which i did a fresh download and install of as well. the only other possible mod interaction would be with fixed launcher or if another mod changed base files which i don't think can happen through vortex when i am not launching from vortex. i am playing the 1.3.1 version of the game.

**Comment by tbeswick96** [comment]
Doubt it's a mod conflict but that's for checking that out anyway.
Could you outline some repro steps and also maybe upload your json config file for me? `(Users\<Your User>\Documents\Mount and Blade II Bannerlord\Configs\YetAnotherPartyOrganiser\Config.json)`

**Comment by KRASK52** [comment]
[Config.TXT](https://github.com/tbeswick96/BannerlordYetAnotherPartyOrganiser/files/4618996/Config.TXT)
Alright saved it as a text. to get the error message so far all i have done is create a new character and save right away, i have tried waiting for 30 seconds before loading but with the same results.  after that it will show up if i save during that initial play through. if i exit to menu load that save and try to save it will crash to desktop no prompt to send info to taleworlds. if i restart the game and load that save the game will fail to create a save or sometimes work just fine. if it fails to create a save it will always do that even after restarting the game and loading that save

I haven't done any testing with just your mod and its requirements beyond creating a character and saving and seeing the pop up. please let me know if i need to clarify anything

**Comment by tbeswick96** [comment]
@KRASK52 Thanks for the detail, pretty certain I found the issue, have done a release that should resolve this, please let me know how you get on

**Comment by tbeswick96** [comment]
Nothing heard, closing
